algo: dqn
batch_size: 64
buffer_size: 100000
episode_length: 25000
epsilon: 0.2
epsilon_end: 0.05
epsilon_speed: 0.99998
evaluate_rate: 50
game_name: snake1v1
gamma: 0.9
hidden_size: 256
lr_a: 0.0001
lr_c: 1.0e-05
max_episodes: 25000
model_episode: 1000
output_activation: softmax
run_redo: null
save_interval: 1000
seed_nn: 1
seed_np: 1
seed_random: 1
target_replace: 100
tau: 0.001
train_redo: false
