algo: dqn
batch_size: 64
buffer_size: 100000
episode_length: 50000
epsilon: 0.2
epsilon_end: 0.05
epsilon_speed: 0.99998
evaluate_rate: 50
game_name: snake1v1
gamma: 0.95
hidden_size: 1024
lr_a: 0.0001
lr_c: 0.0001
max_episodes: 50000
model_episode: 1000
output_activation: softmax
run_redo: null
save_interval: 1000
seed_nn: 20
seed_np: 1
seed_random: 1
target_replace: 100
tau: 0.001
train_redo: false
